Add item requests
PavelDubovik/java-shareit pull request #3
Opened 2022-12-26 21:59 UTC by PavelDubovik

2023-01-02 10:41 UTC, andrew-larkin requested changes
Привет! Отлично, очень качественная работа! Небольшой рефакторинг и мы будем готовы распиливаться это приложение на микросервисы.

2023-01-02 10:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
>      Optional<Booking> findBookingById(Long bookingId);
мне кажется, этот метод доступен по дефолту как findById

2023-01-02 10:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
когда используется пагинация, можно наследоваться от PagingAndSortingRepository

2023-01-04 10:23 UTC, PavelDubovik commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
>      Optional<Booking> findBookingById(Long bookingId);
Да, ты совершено прав

2023-01-05 15:02 UTC, merged